#!/usr/bin/env ruby

require 'pp'

# assumes that all nstrct libraries are in the same directory
EXECUTABLES = { 
  ruby: File.expand_path('../../nstrct-ruby/cross_platform_test', __FILE__),
  java: File.expand_path('../../nstrct-java/cross_platform_test', __FILE__),
  c: File.expand_path('../../nstrct-c/cross_platform_test', __FILE__),
  objc: File.expand_path('../../nstrct-objc/run_cross_platform_test', __FILE__)
}

puts "== testing instruction generation =="
lengths = EXECUTABLES.map do |type, exe|
  data = `#{exe} -g`
  real_length = data.slice!(0..3).unpack('L>')[0]
  "  #{type}: #{data.length} (#{real_length})"
end
puts lengths

puts "== testing instruction processing =="
EXECUTABLES.keys.permutation(2).each do |combination|
  puts "  #{combination[0]} => #{combination[1]}"
  system "  #{EXECUTABLES[combination[0]]} -g | #{EXECUTABLES[combination[1]]} -p"
  puts "    test failed" if $? != 0
end
